### ISSUE TITLE
Mock de l'API Smartfile

### ISSUE THREAD

**Issue by anthonny** [xsellier/easy-reporter#2]
En environnement de developpement, un connexion à **SmartFile** n'est pas nécessaire.
Il faudrait implementer une API pour un developpement local.

Il faudra un exemple de response pour les endpoints suivants:

- [x] copy
- [x] delete
- [x] download
- [x] info
- [x] mkdir
- [x] move
- [x] ping
- [x] rename
- [x] upload
- [x] whoami

On pourrait ensuite faire les endpoints qui correspondent sur l'API exposées par l'application `easy-reporter` et ensuite changer la variable `file.host` dans le fichier de configuration `default.json`.

**Comment by xsellier** [comment]
Pour l'environnement local, SmartFile a été complètement mock.
Parcontre je vais ajouter la possibilité d'avoir ou de ne pas avoir de notifications par email.
